name: ThaiRoStats-ItemEditor
version: '0.0.1-SNAPSHOT'
main: org.rostats.itemeditor.ItemEditorPlugin
api-version: '1.21'
depend: [ThaiRoStats-Core]
commands:
  roitemedit:
    description: Open the Item Attribute Editor GUI.
    usage: /roitemedit
    permission: rostats.itemeditor.admin
permissions:
  rostats.itemeditor.admin:
    description: Allows access to the Item Attribute Editor command.
    default: op